name: Build and Push Docker Image

on:
  push:
    branches:
      - master  # Triggered on PR merge to main

jobs:
  build-and-push:
    name: Build and Push to Docker Hub
    runs-on: ubuntu-latest  # Use GitHub-hosted runner with Docker preinstalled

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          IMAGE_NAME=test-messenger
          IMAGE_TAG=${{ github.sha }}
          docker build -t $IMAGE_NAME:$IMAGE_TAG -f Dockerfile .

      - name: Tag and push image
        run: |
          IMAGE_NAME=test-messenger
          IMAGE_TAG=${{ github.sha }}
          IMAGE_REPO=${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME

          docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_REPO:$IMAGE_TAG
          docker push $IMAGE_REPO:$IMAGE_TAG

      - name: Get Digest from Docker Hub
        id: digest
        run: |
          IMAGE_NAME=test-messenger
          IMAGE_TAG=${{ github.sha }}
          IMAGE_REPO=${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME

          USER_NAME=${IMAGE_REPO%%/*}
          REPO_NAME=${IMAGE_REPO##*/}

          DIGEST=$(curl -s -H "Accept: application/vnd.docker.distribution.manifest.v2+json" \
            "https://index.docker.io/v2/${USER_NAME}/${REPO_NAME}/manifests/${IMAGE_TAG}" \
            | jq -r .config.digest)

          echo "digest=$DIGEST"
          echo "digest=$DIGEST" >> $GITHUB_OUTPUT

      - name: Clone deploy repo and update staging values
        run: |
          git config --global user.name "GitOps Bot"
          git config --global user.email "bot@example.com"

          git clone https://x-access-token:${{ secrets.GH_ACTIONS_PAT }}@github.com/cjmak0/test-messenger-deploy.git
          cd test-messenger-deploy
          git checkout -b update-staging-${{ github.sha }} origin/staging

          yq e '.image = {"repository": "cjmak0/test-messenger", "digest": "${{ steps.digest.outputs.digest }}"}' -i envs/staging/values.yaml

          git add envs/staging/values.yaml
          git commit -m "Update image digest to ${{ steps.digest.outputs.digest }}"
          git push origin HEAD

      - name: Create PR to staging
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GH_ACTIONS_PAT }}
          repository: cjmak0/test-messenger-deploy
          base: staging
          branch: update-staging-${{ github.sha }}
          title: "Update image digest to ${{ steps.digest.outputs.digest }}"
          commit-message: "Update image digest to ${{ steps.digest.outputs.digest }}"
          body: |
            This PR updates the Helm deployment to use image:
            `cjmak0/test-messenger@${{ steps.digest.outputs.digest }}`


