name: Build and Push Docker Image

on:
  push:
    branches:
      - master  # Triggered on PR merge to master

env:
  GITHUB_USER: ${{ secrets.GH_USER }}
  DEPLOY_REPO: ${{ secrets.DEPLOY_REPO }}
  CODE_REPO: ${{ secrets.CODE_REPO }}

jobs:
  build-and-push:
    name: Build and Push to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          IMAGE_NAME=$CODE_REPO
          IMAGE_TAG=${{ github.sha }}
          docker build -t $IMAGE_NAME:$IMAGE_TAG -f Dockerfile .

      - name: Tag and push image
        run: |
          IMAGE_NAME=$CODE_REPO
          IMAGE_TAG=${{ github.sha }}
          IMAGE_REPO=${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME

          docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_REPO:$IMAGE_TAG
          docker push $IMAGE_REPO:$IMAGE_TAG

      - name: Get Digest from Docker Hub
        id: digest
        run: |
          set -e

          IMAGE_NAME=$CODE_REPO
          IMAGE_TAG=${{ github.sha }}
          IMAGE_REPO=${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME

          echo "Inspecting image: $IMAGE_REPO:$IMAGE_TAG"
          DIGEST=$(docker buildx imagetools inspect $IMAGE_REPO:$IMAGE_TAG --format '{{json .}}' | jq -r '.manifest.digest')

          echo "Digest: $DIGEST"
          echo "digest=$DIGEST" >> "$GITHUB_OUTPUT"

      - name: Use Digest
        run: echo "Image Digest is ${{ steps.digest.outputs.digest }}"

      - name: Clone deploy repo and update staging values
        run: |
          git config --global user.name "GitOps Bot"
          git config --global user.email "bot@example.com"

          git clone https://x-access-token:${{ secrets.GH_ACTIONS_PAT }}@github.com/${{ env.GITHUB_USER }}/${{ env.DEPLOY_REPO }}.git
          cd ${{ env.DEPLOY_REPO }}

          git fetch origin staging
          git checkout -b update-staging-${{ github.sha }} origin/staging

          yq e '.image = {"repository": "${{ env.GITHUB_USER }}/${{ env.CODE_REPO }}", "digest": "${{ steps.digest.outputs.digest }}"}' -i envs/staging/values.yaml

          git add envs/staging/values.yaml
          git commit -m "Update image digest to ${{ steps.digest.outputs.digest }}"
          git push origin HEAD

      - name: Create PR in deploy repo
        run: |
          cd $DEPLOY_REPO
          gh pr create \
            --repo "$GITHUB_USER/$DEPLOY_REPO" \
            --base staging \
            --head update-staging-${{ github.sha }} \
            --title "Update image digest for staging release" \
            --body "This PR updates the Helm deployment to use image:\n${GITHUB_USER}/${CODE_REPO}@${{ steps.digest.outputs.digest }}"
        env:
          GH_TOKEN: ${{ secrets.GH_ACTIONS_PAT }}
