name: Build and Push Docker Image

on:
  push:
    branches:
      - master  # Triggered on PR merge to main

jobs:
  build-and-push:
    name: Build and Push to Docker Hub
    runs-on: ubuntu-latest  # Use GitHub-hosted runner with Docker preinstalled

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PWD }}" | docker login -u "${{ secrets.DOCKER_UID }}" --password-stdin

      - name: Build Docker image
        run: |
          IMAGE_NAME=test-messenger
          IMAGE_TAG=${{ github.sha }}
          docker build -t $IMAGE_NAME:$IMAGE_TAG -f Dockerfile .

      - name: Tag and push image
        run: |
          IMAGE_NAME=test-messenger
          IMAGE_TAG=${{ github.sha }}
          IMAGE_REPO=${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME

          docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_REPO:$IMAGE_TAG
          docker push $IMAGE_REPO:$IMAGE_TAG
